spring.application.name: http-hdfs
server.port: 8901
debug: false

xml:
  site:
    core: /etc/hadoop/conf/core-site.xml
    hdfs: /etc/hadoop/conf/hdfs-site.xml


spring:
  http:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB